services:
  redpanda:
    image: redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp 1
      - --memory 512M
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD", "rpk", "cluster", "info"]
      interval: 10s
      timeout: 5s
      retries: 5

  kestra:
    image: kestra/kestra:latest
    container_name: kestra
    pull_policy: always
    user: "root"
    command: server standalone
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/app/project
    environment:
      SECRET_DATABASE_URL: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnNwb3J0MjAyNEBob3N0LmRvY2tlci5pbnRlcm5hbDo1NDMyL3Nwb3J0X3BvYw==
      SECRET_GOOGLE_MAPS_API_KEY: QUl6YVN5Q3hHVjJROEZROGVqQkJ2bU9VVzZYcGZxbmxlcnF3MmRN
      SECRET_SLACK_BOT_TOKEN: eG94Yi0xMTM4OTE0NDA0NjM1OC0xMTM3NTgzNjYwMzU0My1wYmhFaTl6NWtIbXNzSjJOZHhQMlFBaGk=
      SECRET_SLACK_CHANNEL: c3BvcnQtZGF0YS1wb2M=
      SECRET_BONUS_RATE: MC4wNQ==
      SECRET_WELLNESS_MIN_ACTIVITIES: MTU=
      SECRET_WELLNESS_DAYS: NQ==
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://host.docker.internal:5432/kestra
            driverClassName: org.postgresql.Driver
            username: postgres
            password: sport2024
        kestra:
          server:
            basic-auth:
              enabled: false
          repository:
            type: postgres
          storage:
            type: local
            local:
              base-path: "/app/storage"
          queue:
            type: postgres
          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  kestra-data: